export const actionTypes = {
    FETCH_START: "FETCH_START",
    FETCH_END: "FETCH_END",
    USER_LOGIN: "USER_LOGIN",
    USER_REGISTER: "USER_SIGNUP",
    GET_USER_SESSION: "GET_USER_SESSION",
    SET_MESSAGE: "SET_MESSAGE",
    USER_AUTH:"USER_AUTH",
    GET_USER_SESSION_SUCCESS:"GET_USER_SESSION_SUCCESS",
}